services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm run dev

  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/app
    depends_on:
      - backend
    command: npm run start
