services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    labels:
      - dev.orbstack.domains=back.anymem.orb.local

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"
    labels:
      - dev.orbstack.domains=front.anymem.orb.local

  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/app
    depends_on:
      - backend
    command: npm run start
