services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    labels:
      - dev.orbstack.domains=back.anymem.orb.local
    stop_signal: SIGINT
    stop_grace_period: 1s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/anymem
    labels:
      - dev.orbstack.domains=front.anymem.orb.local
    stop_signal: SIGINT
    stop_grace_period: 1s

  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run start
    stop_signal: SIGINT
    stop_grace_period: 1s
