name: anymem
services:
  web:
    platform: linux/amd64
    image: anymem-web-prod:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.anymem.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      - traefik.http.middlewares.anymem-redirect-to-non-www.redirectregex.regex=^https?://www.${DOMAIN}/(.*)
      - traefik.http.middlewares.anymem-redirect-to-non-www.redirectregex.replacement=https://${DOMAIN}/$${1}
      - traefik.http.middlewares.anymem-redirect-to-non-www.redirectregex.permanent=true
      - traefik.http.routers.anymem.middlewares=anymem-redirect-to-non-www
      - traefik.http.routers.anymem.entrypoints=web
      - traefik.http.routers.anymem.service=anymem
      - traefik.http.services.anymem.loadbalancer.server.port=3000
    networks:
      - traefik-containers

networks:
  traefik-containers:
    external: true
