-- this is a backup from the supabase sql editor

CREATE TABLE IF NOT EXISTS
  users (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    clerk_user_id TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
  );

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  decks (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title TEXT,
    user_id BIGINT REFERENCES users (id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
  );

ALTER TABLE decks ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  cards (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT REFERENCES users (id),
    deck_id BIGINT REFERENCES decks (id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    front_content TEXT,
    back_content TEXT,
    meta jsonb
  );

ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
